### ISSUE TITLE
ZDFtivi: Hoster möglich?

### ISSUE THREAD

**Issue by meinnamehier** [iNaD/download-station-zdfmediathek#10]
Hallo,

keine Ahnung, ob hier richtig: Ich würde gerne auf ZDFtivi downloaden http://www.tivi.de/mediathek/
Hierfür einen Hoster zu haben, wäre toll!

**Comment by iNaD** [comment]
Habe kurz drüber geschaut und ja wäre möglich. Muss ich mal schauen, wann ich Zeit dazu finde.

Lasse mir mal eine kleine Notiz hier ;)

```
<meta id="php_data" name="param" content="/tiviVideos/beitrag/X/Y?view=flashXml">
```

**Comment by iNaD** [comment]
Tivi läuft nun unter https://www.zdf.de/kinder und wird somit von dem neuen Projekt https://github.com/iNaD/ds-mediatheken unterstützt
