### ISSUE TITLE
Neo Magazin wird nicht als Teil der ZDF Mediathek erkannt

### ISSUE THREAD

**Issue by kronn** [iNaD/download-station-zdfmediathek#12]
Ich wollte das Video, das hier angeboten wird herunterladen:

https://www.neo-magazin-royale.de/zdi/artikel/136348/neo-magazin-royale-vom-10-11-2016.html

Leider erkennt die Downloadstation nicht, dass es sich um die ZDF Mediathek handelt, vermutlich weil eine spezielle Domain verwendet wird.

Meine DiskStation: DS215j
Installierte DSM-Version: DSM 6.0.2-8451 Update 2
DSM-Datum: 2016/10/05

**Comment by iNaD** [comment]
Korrekt. Versuche es solange mit diesem Link
https://www.zdf.de/comedy/neo-magazin-mit-jan-boehmermann/neo-magazin-royale-mit-jan-boehmermann-vom-12-november-2016-100.html

Das sollte ja die korrekte Folge sein? Leider ist das alles so komisch
gesplittet worden...

Am 13.11.2016 8:01 nachm. schrieb "Matthias Viehweger" <
notifications@github.com>:

**Comment by kronn** [comment]
Habe jetzt einen passende RSS-Feed gefunden, damit geht es: https://www.zdf.de/rss/zdf/comedy/neo-magazin-mit-jan-boehmermann

Danke!
