### ISSUE TITLE
Weder ARD noch ZDF Mediatheken starten Download

### ISSUE THREAD

**Issue by TheFive** [iNaD/download-station-zdfmediathek#13]
Hallo,

ich hab versucht mit dem ZDF Hoster den folgenden Film runterzuladen:
https://www.zdf.de/filme/wilsberg/bittere-pillen-102.html

Der Download startet nicht, ich bekomme in /var/log/message
synoscgi_SYNO.DownloadStation2.Task_2_get[4734]: download_task.cpp:942 Failed to get task record id = 41

Da ich den gleichen Fehler auch in der ARD Mediathek habe, gehe ich davon aus, das es eher an meiner Synology liegt.

Disk Station Version:
DSM 6.0.2-8451 Update 4

Download Station Version
![image](https://cloud.githubusercontent.com/assets/6240370/20461922/8eabca2e-af0d-11e6-903e-9c53b0926b23.png)

Ich hatte allerdings das ganze noch nie am laufen.

Hast Du irgendeine Idee für mich, wo ich suchen / hingreifen kann ?

**Comment by iNaD** [comment]
Hmm, das liest sich wirklich eher wie ein Fehler in der Download Station selber. Hast du die Download Station schon mal neu installiert? Sollte doch eigentlich möglich sein.

**Comment by TheFive** [comment]
ich schau mal. Das Ding hat schon ein paar Jahre auf dem Buckel (ist ne DS111), aber hat eigentlich immer alle Updates bekommen. Da das NAS meistens der grösste Speicher im Haus ist, ist das mit den Daten immer so eine Sache :-)

**Comment by TheFive** [comment]
Ich habe die Download Station deinstalliert und neu installiert. 
Jetzt geht es. Danke für den Tipp.

Christoph
