### ISSUE TITLE
WDR Mediathek - funktioniert nicht

### ISSUE THREAD

**Issue by Tho-Gra** [iNaD/download-station-zdfmediathek#14]
Moin,

Bei mir funktioniert das leider nicht. 

Verwendeter Link : http://www1.wdr.de/fernsehen/feuer-und-flamme/sendungen/feuer-und-flamme-folge-eins-100.html

Grüße

Tho-Gra

**Comment by iNaD** [comment]
Hi Tho-Gra,

ja leider funktionieren die Provider aktuell (fast?) alle nicht. Habe immer noch keine Zeit gefunden, um diese wieder an den neuesten Stand der Mediatheken anzupassen.

**Comment by philruediger** [comment]
Hi zusammen, 

ich habe den Provider aus der zdfmediathek auf den neusten Stand gebracht. Der ApiToken wird nicht mehr aus der Config gelesen sondern ist direkt im HTTP-Content verfügbar. 

Grüße.

[zdfmediathek.zip](https://github.com/iNaD/download-station-zdfmediathek/files/1189979/zdfmediathek.zip)

**Comment by iNaD** [comment]
Hi @philruediger,
vielen Dank für deine Mühe. Ich schaue mir die Änderungen mal die Tage an.

**Comment by iNaD** [comment]
WDR wird in Zukunft im neuen Provider implementiert. Alles über den Fortschritt findet ihr hier: https://github.com/iNaD/ds-mediatheken/issues/1
