### ISSUE TITLE
Titel werden nicht mehr heruntergeladen - ZDF Mediathek - Synology DS716+II

### ISSUE THREAD

**Issue by sebastian811** [iNaD/download-station-zdfmediathek#15]
Hallo Daniel,
ich habe deine Erweiterung für die Synology Download Station in den letzten Wochen sehr gerne immer mal wieder benutzt um aus den Mediatheken von ARD und ZDF herunterzuladen. 
Leider kann ich derzeit nichts mehr aus der ZDF Mediathek herunterladen.
Beispielsweise:
https://www.zdf.de/dokumentation/dokumentation-sonstige/jagd-nach-dem-himmelsfeuer-dem-104.html
aber auch andere, aktuelle Sendungen klappen nicht. Es wird jeweils nur eine wenige KB große html Datei angelegt. ARD klappt hingegen ohne Probleme.
Ich verwende eine DS716+II.

Vielen Dank für deine Hilfe und deine super coole Erweiterung!

Viele Grüße
Sebastian

**Comment by philruediger** [comment]
Hi Sebastian,

schaue mal hier: https://github.com/iNaD/download-station-zdfmediathek/issues/14

Dort habe ich eine host-Datei mit Anpassungen des Scripts hochgeladen, bis der Autor ein neues Release erstellt.

Grüße 
Phil

**Comment by sebastian811** [comment]
Hallo Phil,


besten Dank!

Probiere ich mal aus.

Viele Grüße

Sebastian

**Comment by indiean** [comment]
Hallo zusammen,

ich habe die upgedatete .host von @philruediger installiert.
Leider kann ich auch mit dieser z.B. die neueste Folge Aktenzeichen XY - `https://www.zdf.de/gesellschaft/aktenzeichen-xy-ungeloest/aktenzeichen-xy-ungeloest-vom-6-september-2017-100.html` nicht herunterladen. Es wird nur eine Mini-Datei heruntergeladen.

Vorgehen: Ich habe die alte .host deinstalliert und dann die neue installiert.

Könnt ihr das so bestätigen?

Vielen Dank und viele Grüße
indiean

**Comment by iNaD** [comment]
Hi, entschuldigt die späte Antwort 😞 

Leider gab es sowohl privat als auch beruflich einige Dinge, welche mich aufgehalten haben an den Mediatheken zu arbeiten. Auch bin ich immer noch nicht dazu gekommen meine Synology wieder zum Laufen zu bekommen.

Um mir vieles einfacher zu machen, habe ich vor längerer Zeit angefangen einen anderen Ansatz zu wählen und alle Mediatheken unter einen Hut zu bringen. Leider bin ich nicht sehr weit gekommen. Vorhin habe ich mich nochmal kurz eingelesen und gesehen, dass zumindest das ZDF schon so gut wie fertig war.

Lange Geschichte, kurze Antwort: Im Anhang habe ich eine Host Datei. Wäre lieb wenn die einer testen könnte. Diese unterstützt aktuell nur Links von zdf.de.

Sollte alles soweit funktionieren, so würde ich mich daran machen, dass ich die anderen Mediatheken auch noch implementiere und euch dann bescheid gebe, wo es die finale Version gibt.

LG,
iNaD aka. Daniel

[mediathek.zip](https://github.com/iNaD/download-station-zdfmediathek/files/1325448/mediathek.zip)

**Comment by indiean** [comment]
Hi iNaD,

vielen Dank für deinen Einsatz. :)
Ich habe gerade einen Test-Download beim ZDF gemacht. Dieser hat funktioniert.
Also erstmal scheint es zu funktionieren.

Vielen Dank!
VG
indiean

**Comment by iNaD** [comment]
Kleines Update von mir:

Ich habe ein wenig den Code aufgeräumt und 3sat hinzugefügt.

Da nun die Mediathek dynamisch bestimmt wird (anhand der URL), wäre es cool wenn jemand die neue Version testen könnte. [mediathek.zip](https://github.com/iNaD/download-station-zdfmediathek/files/1334742/mediathek.zip)

Insofern diese läuft, werde ich anfangen die weiteren Mediatheken einzubinden und eine erste Version zu veröffentlichen.

**Comment by indiean** [comment]
Update von mir:
1x ZDF erfolgreich
1x 3sat erfolgreich

**Comment by iNaD** [comment]
Oh sehr schön 👍 

Dann kann ich die Tage ja richtig loslegen 😀

**Comment by iNaD** [comment]
Dann mache ich hier mal dicht. Vielen Dank für euer Input.

Den ersten Release (und auch alle folgenden) findet ihr hier: https://github.com/iNaD/ds-mediatheken/releases
