### ISSUE TITLE
https://www.zdf.de/filme/maximilian/maximilian---das-spiel-von-macht-und-liebe-3-historischer-dreiteiler-100.html

### ISSUE THREAD

**Issue by cplur** [iNaD/download-station-zdfmediathek#16]
Downloading part 1 to 3 of Maximilian fram the ZDF Mediathek to Synology Diskstation  with 
DSM 6.1.3-15152 Update 5 Fails. Download Station is just downloading the html file.

**Comment by iNaD** [comment]
Try it with the new Provider [iNaD/ds-mediatheken](https://github.com/iNaD/ds-mediatheken)
