### ISSUE TITLE
ZDF Mediathek download geht nicht

### ISSUE THREAD

**Issue by Papierverbieger** [iNaD/download-station-zdfmediathek#18]
Hallo!
Entweder ich bin zu doof oder der Download vom ZDF Videos geht nicht mehr.
Von der ARD klappt das ohne Probleme. Aber der Versuch z B eine Folge Tannenbach auf meine NAS DS213+ zu laden schlägt fehl und er läd nur die HTML Seite. Könnt Ihr mir bitte einen Tip geben?

MfG
Jan

**Comment by iNaD** [comment]
Hi Papierverbieger / Jan,

schau dir mal das neue Plugin an: https://github.com/iNaD/ds-mediatheken
Es ersetzt dieses und bietet aktuell zudem noch ARD, RBB, WDR und One (ehemals Einsfestival).

Sobald ich wieder Zeit finde, folgen auch noch Arte, NDR und co. So müsst ihr nur noch eine Datei auf dem neuesten Stand halten und nicht jede Mediathek einzeln updaten 😉
