### ISSUE TITLE
Es werden nur HTML Seiten geladenen

### ISSUE THREAD

**Issue by walter1959** [iNaD/download-station-zdfmediathek#3]
Beispiel ZDF Mediathek: http://www.zdf.de/ZDFmediathek#/beitrag/video/2251610/Fährt-Auto-Deutschland-vor-die-Wand

Benutzte Diskstation:
Modellname DS212j
DSM-Version
DSM 5.1-5004
Downloadstation: 3.5-2706

**Comment by iNaD** [comment]
Hi @walter1959,
ich habe das mal mit der Debug Version getestet und bei mir wird eine korrekte URL ausgespuckt. Sicher, dass es dieser Link war?

Falls ja, so hier eine kleine Debug Anleitung (benötigt SSH Zugriff):

1. [Diese Version](http://1drv.ms/1w3vJgl) vom ZDF Mediathek Provider herunterladen
2. Alte Version löschen
3. Neue Version hinzufügen
4. Via SSH auf die Disk Station zugreifen und mit `cd /tmp` in den temporären Ordner gehen
5. Download hinzufügen
6. Nach Abschluss des Downloads die Ausgabe von `tail zdf-mediathek.log` hier schreiben

Ich hoffe, dass wir dem Problem auf die Schliche kommen.

**Comment by walter1959** [comment]
Hallo Herr Gehn,

hat leider auch niciht geklappt. Die Logdatei steht unten.

Grüße

Walter Mayerhofer


DiskStation_212> export zdf-mediathek.log
-sh: export: zdf-mediathek.log: bad variable name
DiskStation_212> tail zdf-mediathek.log
URL: http://www.zdf.de/ZDFmediathek/hauptnavigation/startseite#/beitrag/video/1876386/Trailer-zu-VERBRECHEN:-Summertime
GetDownloadInfo called
Getting download url for http://www.zdf.de/ZDFmediathek/hauptnavigation/startseite#/beitrag/video/1876386/Trailer-zu-VERBRECHEN:-Summertime
ID is 1876386
Getting XML data from http://zdf.de/ZDFmediathek/xmlservice/web/beitragsDetails?id=1876386&ak=web
Failed to retrieve XML.
URL: http://www.zdf.de/ZDFmediathek/hauptnavigation/startseite#/beitrag/video/1876386/Trailer-zu-VERBRECHEN:-Summertime
DiskStation_212>

**Comment by iNaD** [comment]
Habe ich mir angeschaut,

schau mal, ob es jetzt funktioniert mit [dieser Version](http://1drv.ms/1KqbnIG)

**Comment by walter1959** [comment]
Hallo Daniel,

getestet, es funktioniert nun.

Besten Dank und Grüße

Walter

**Comment by iNaD** [comment]
Gut, dann werde ich gleich eine neue Version veröffentlichen.
