### ISSUE TITLE
Probleme mit Montagskino auf ZDF

### ISSUE THREAD

**Issue by mac1974** [iNaD/download-station-zdfmediathek#4]
Link: http://www.zdf.de/ZDFmediathek#/kanaluebersicht/2288228/sendung/Montagskino-im-ZDF
Titel: Stieg Larsson: Verblendung
Diskstation DS213J
Version DSM 5.1-5022

**Comment by iNaD** [comment]
Hallo mac1974,

bei dem Link handelt es sich nicht um ein Video, sondern eine "Kanalübersicht".
Für diese existiert - noch - keine Möglichkeit alle Videos zu erfassen und zu downloaden.

Wenn man nun auf das Video (Stieg Larsson: Verblendung)[http://www.zdf.de/ZDFmediathek#/beitrag/video/2316506/%22Stieg-Larsson:-Verblendung%22] geht, dann kann man diesen Link kopieren und auch herunterladen.
**Aber** da der Film FSK16 besitzt, ist dies nur zwischen 22 und 6 Uhr möglich.
Zur Zeit erhält man nur das Hinweis Video hierzu.

Ich hoffe ich konnte dir helfen und du kannst heute Abend ab 22 Uhr mit dem Download beginnen.

**Comment by mac1974** [comment]
Hi,
danke für die schnelle Hilfe und die perfekte Ergänzungen zur DS ;-)
Ich probiere es gleich mal um 22 Uhr.
