### ISSUE TITLE
Plugins laden nur .html

### ISSUE THREAD

**Issue by nail299** [iNaD/download-station-zdfmediathek#5]
Hallo Daniel,

ich nutze eine Synology DS214 mit DSM 5.0-4528, die DownloadStation Version ist 3.4-2558 und habe Deine (aktuellsten) Host Dateien (ZDF, NDR etc) installiert.

Leider lädt mir die Syno nur die .html Dateien herunter, egal welche Mediathek ich auswähle.
Beispiel:
Eine komplette Folge von ZAPP (NDR) versuche ich über folgende URL über die DownloadStation zu laden:
http://www.ndr.de/fernsehen/sendungen/zapp/ZAPP-Das-Medienmagazin,zapp8424.html

Eine Folge bei 3sat klappte auch nicht:
http://www.3sat.de/mediathek/?mode=play&obj=48114

Ich habe es mit allen anderen Mediatheken (SWR, arte+ etc.) probiert, leider das gleiche Ergebnis.

Was mache ich falsch?

Danke Dir vorab für eine Antwort und viele Grüße
Peter Schmitt

**Comment by iNaD** [comment]
Moin Peter,

bei mir haben beide Links funktioniert. Bei mir läuft von DownloadStation die Version 3.5-xxxx. Kannst du diese ggf. aktualisieren und erneut die Downloads testen?

Solltest du nicht aktualisieren können bzw. es nach einer Aktualisierung immer noch nicht funktionieren, so würde ich dir eine Debug Version von einem der Provider zukommen lassen.

Grüße,
Daniel

**Comment by nail299** [comment]
Moin Daniel,
habe die DS auf die akteulle 3.5-2706 geupdatet. Es funktioniert!
Hätte ich auch gleich probieren können.

Danke Dir für Deine schnelle Antwort und die host-Dateien, super Arbeit!

Grüße,
Peter

**Comment by iNaD** [comment]
Na dann noch viel Spaß weiterhin.

----- Ursprüngliche Nachricht -----
Von: "nail299" <notifications@github.com>
Gesendet: ‎23.‎02.‎2015 11:18
An: "iNaD/download-station-zdfmediathek" <download-station-zdfmediathek@noreply.github.com>
Cc: "Daniel Gehn" <inad.gamer@gmail.com>
Betreff: Re: [download-station-zdfmediathek] Plugins laden nur .html (#5)

Moin Daniel,
habe die DS auf die akteulle 3.5-2706 geupdatet. Es funktioniert!
Hätte ich auch gleich probieren können.
Danke Dir für Deine schnelle Antwort und die host-Dateien, super Arbeit!
Grüße,
Peter
