### ISSUE TITLE
Beitrag mit Größe null

### ISSUE THREAD

**Issue by jfedermann** [iNaD/download-station-zdfmediathek#7]
Hallo,

Ich habe über die ZDF Mediathek versucht, den Link http://webapp.zdf.de/mediathek/page/beitrag?aID=2592072&cID=2078040 zu laden. Es wird eine Datei mit dem Namen Beitrag erstellt. Diese hat die Größe Null. Mit der ARD Mediathek geht alles gut.

Ich nutze eine ds213j

Viele Grüße
Jürgen

**Comment by iNaD** [comment]
Moin Jürgen,

ich werde mir das demnächst mal ansehen, solange versuche es über diesen Link: http://www.zdf.de/ZDFmediathek/#/beitrag/video/2592072/Schattenriss
Der sollte funktionieren ;)

Weihnachtliche Grüße,
Daniel
