### ISSUE TITLE
ZDF Mediathek 22:00 uhr sperre

### ISSUE THREAD

**Issue by michaestraub** [iNaD/download-station-zdfmediathek#9]
Hi, tolles Projekt, im Gegensatz zur ARD Mediathek, funktionieren Zeitgesperrte Inhalte auf ZDF leider nicht zum sofortigen Download, gibts da ne Möglichkeit das zu integrieren? Mit MediathekView funktioniert es derzeit.

THX Michael

**Comment by iNaD** [comment]
Da wüsste ich nicht, wie das machbar ist, da man leider keinerlei Kontrolle über die Download Station an sich hat, sondern nur Dateinamen und den Download übergeben kann.
Ich werde mal schauen, ob ich eine Lösung finde

**Comment by iNaD** [comment]
Tivi läuft nun unter `https://www.zdf.de/kinder` und wird somit von dem neuen Projekt https://github.com/iNaD/ds-mediatheken unterstützt

**Comment by iNaD** [comment]
Wird hier nun weiter verfolgt: https://github.com/iNaD/ds-mediatheken/issues/2
